// Generated by Microsoft TypeSpec

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/document/v1/v1.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The template for omitting properties.
type ProtoDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoDocument) Reset() {
	*x = ProtoDocument{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoDocument) ProtoMessage() {}

func (x *ProtoDocument) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoDocument.ProtoReflect.Descriptor instead.
func (*ProtoDocument) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoDocument) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProtoDocument) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProtoDocument) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProtoDocumentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ProtoDocument       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoDocumentList) Reset() {
	*x = ProtoDocumentList{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoDocumentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoDocumentList) ProtoMessage() {}

func (x *ProtoDocumentList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoDocumentList.ProtoReflect.Descriptor instead.
func (*ProtoDocumentList) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoDocumentList) GetItems() []*ProtoDocument {
	if x != nil {
		return x.Items
	}
	return nil
}

type DocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	PriceUsd      int32                  `protobuf:"varint,4,opt,name=priceUsd,proto3" json:"priceUsd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentResponse) Reset() {
	*x = DocumentResponse{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResponse) ProtoMessage() {}

func (x *DocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResponse.ProtoReflect.Descriptor instead.
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{2}
}

func (x *DocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentResponse) GetPriceUsd() int32 {
	if x != nil {
		return x.PriceUsd
	}
	return 0
}

type ListDocumentsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsReq) Reset() {
	*x = ListDocumentsReq{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsReq) ProtoMessage() {}

func (x *ListDocumentsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsReq.ProtoReflect.Descriptor instead.
func (*ListDocumentsReq) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{3}
}

type ListDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentResponse    `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsResponse) Reset() {
	*x = ListDocumentsResponse{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsResponse) ProtoMessage() {}

func (x *ListDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsResponse.ProtoReflect.Descriptor instead.
func (*ListDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ListDocumentsResponse) GetDocuments() []*DocumentResponse {
	if x != nil {
		return x.Documents
	}
	return nil
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{5}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Req           *ListDocumentsReq      `protobuf:"bytes,1,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDocumentsRequest) Reset() {
	*x = ListDocumentsRequest{}
	mi := &file_proto_document_v1_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDocumentsRequest) ProtoMessage() {}

func (x *ListDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_document_v1_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_document_v1_v1_proto_rawDescGZIP(), []int{6}
}

func (x *ListDocumentsRequest) GetReq() *ListDocumentsReq {
	if x != nil {
		return x.Req
	}
	return nil
}

var File_proto_document_v1_v1_proto protoreflect.FileDescriptor

const file_proto_document_v1_v1_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/document/v1/v1.proto\x12\vdocument.v1\"K\n" +
	"\rProtoDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"E\n" +
	"\x11ProtoDocumentList\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.document.v1.ProtoDocumentR\x05items\"n\n" +
	"\x10DocumentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bpriceUsd\x18\x04 \x01(\x05R\bpriceUsd\"\x12\n" +
	"\x10ListDocumentsReq\"T\n" +
	"\x15ListDocumentsResponse\x12;\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1d.document.v1.DocumentResponseR\tdocuments\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x14ListDocumentsRequest\x12/\n" +
	"\x03req\x18\x01 \x01(\v2\x1d.document.v1.ListDocumentsReqR\x03req2\xb8\x01\n" +
	"\x0fDocumentService\x12M\n" +
	"\vGetDocument\x12\x1f.document.v1.GetDocumentRequest\x1a\x1d.document.v1.DocumentResponse\x12V\n" +
	"\rListDocuments\x12!.document.v1.ListDocumentsRequest\x1a\".document.v1.ListDocumentsResponseb\x06proto3"

var (
	file_proto_document_v1_v1_proto_rawDescOnce sync.Once
	file_proto_document_v1_v1_proto_rawDescData []byte
)

func file_proto_document_v1_v1_proto_rawDescGZIP() []byte {
	file_proto_document_v1_v1_proto_rawDescOnce.Do(func() {
		file_proto_document_v1_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_document_v1_v1_proto_rawDesc), len(file_proto_document_v1_v1_proto_rawDesc)))
	})
	return file_proto_document_v1_v1_proto_rawDescData
}

var file_proto_document_v1_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_document_v1_v1_proto_goTypes = []any{
	(*ProtoDocument)(nil),         // 0: document.v1.ProtoDocument
	(*ProtoDocumentList)(nil),     // 1: document.v1.ProtoDocumentList
	(*DocumentResponse)(nil),      // 2: document.v1.DocumentResponse
	(*ListDocumentsReq)(nil),      // 3: document.v1.ListDocumentsReq
	(*ListDocumentsResponse)(nil), // 4: document.v1.ListDocumentsResponse
	(*GetDocumentRequest)(nil),    // 5: document.v1.GetDocumentRequest
	(*ListDocumentsRequest)(nil),  // 6: document.v1.ListDocumentsRequest
}
var file_proto_document_v1_v1_proto_depIdxs = []int32{
	0, // 0: document.v1.ProtoDocumentList.items:type_name -> document.v1.ProtoDocument
	2, // 1: document.v1.ListDocumentsResponse.documents:type_name -> document.v1.DocumentResponse
	3, // 2: document.v1.ListDocumentsRequest.req:type_name -> document.v1.ListDocumentsReq
	5, // 3: document.v1.DocumentService.GetDocument:input_type -> document.v1.GetDocumentRequest
	6, // 4: document.v1.DocumentService.ListDocuments:input_type -> document.v1.ListDocumentsRequest
	2, // 5: document.v1.DocumentService.GetDocument:output_type -> document.v1.DocumentResponse
	4, // 6: document.v1.DocumentService.ListDocuments:output_type -> document.v1.ListDocumentsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_document_v1_v1_proto_init() }
func file_proto_document_v1_v1_proto_init() {
	if File_proto_document_v1_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_document_v1_v1_proto_rawDesc), len(file_proto_document_v1_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_document_v1_v1_proto_goTypes,
		DependencyIndexes: file_proto_document_v1_v1_proto_depIdxs,
		MessageInfos:      file_proto_document_v1_v1_proto_msgTypes,
	}.Build()
	File_proto_document_v1_v1_proto = out.File
	file_proto_document_v1_v1_proto_goTypes = nil
	file_proto_document_v1_v1_proto_depIdxs = nil
}
